### ISSUE TITLE
Ask for password

### ISSUE THREAD

**Issue by wojciechsura** [lukasz-wronski/vscode-ftp-sync#188] opened 2017-06-30 07:28 UTC
The extension seems to be very useful, but requires me to store plaintext password for my FTP account in settings file. Would it be possible to display dialog when there's no password, such that I might have entered it every time I needed to perform operations on FTP?

**Comment by MarceI** [comment] 2017-07-03 04:05
Dupe of #110 and #137 but I agree, if password is empty and is required (login attempted but fails without password) then a prompt for password input should be triggered.

**Comment by hajekj** [comment] 2017-08-23 21:07
Closed by #199

**Closed by hajekj** 2017-08-23 21:07 UTC
