### ISSUE TITLE
GoDaddy Connection

### ISSUE THREAD

**Issue by gitstray** [lukasz-wronski/vscode-ftp-sync#159] opened 2017-05-01 02:49 UTC
Not sure why but I keep getting an error when connecting to a GoDaddy server. I tested this on multiple servers and it works fine on those, but there is something up with GoDaddy Servers when syncing.

Ftp-sync: sync error: Error: read ECONNRESET

**Comment by kalieye** [comment] 2017-05-01 06:07
Duplicate of #24

**Closed by kalieye** 2017-05-01 06:07 UTC
