### ISSUE TITLE
Upload on Save doesnt work

### ISSUE THREAD

**Issue by perfecto25** [lukasz-wronski/vscode-ftp-sync#154] opened 2017-04-21 18:44 UTC
running VS Code on centos 7, my ftp-sync.json 

{
    "remotePath": "/opt",
    "host": "ny02",
    "username": "root",
    "password": "",
    "port": 22,
    "secure": true,
    "protocol": "sftp",
    "uploadOnSave": true,
    "passive": false,
    "debug": true,
    "privateKeyPath": "/root/.ssh/id_rsa",
    "passphrase": null,
    "ignore": [
        "\\.vscode",
        "\\.git",
        "\\.DS_Store"
    ],
    "generatedFiles": {
        "uploadOnSave": true,
        "extensionsToInclude": [],
        "path": ""
    }
}

every time i save a local file, it doesnt get FTPd to the target. I have to do this manually. Am I missing a param?

**Comment by pmingram** [comment] 2017-04-22 11:11
Same thing here on Windows 10.

**Comment by jhvanderschee** [comment] 2017-04-24 11:42
Same on Linux

**Comment by amartacus** [comment] 2017-04-24 13:53
It seems like the Visual Studio 1.11 update broke the upload on save functionality. :(

**Comment by amartacus** [comment] 2017-04-24 14:24
Update - FYI, try reinstalling the extension. After upgrading to VS Code 1.11 I was able to get ftp-sync to start working again.

**Comment by pmingram** [comment] 2017-04-24 14:33
Mine was on a fresh install of VS Code, as I had never used it before and wanted to see if it was feasible to move from PHPStorm.

**Comment by fmrogers** [comment] 2017-04-27 09:00
Not sure if this will help but after reinstalling VS Code (and deleting the setting folder from my user folder), i finally got it working again.

Also these new lines in the confguration:

"generatedFiles": {
"uploadOnSave": true,
"extensionsToInclude": [],
"path": ""
}

This may be incidental but i set the "path" property to the local path of my project. ie' "D:/foo/bar/". 

Not sure if it was the reinstall or the change in "path" but it's all working again for me. Maybe somebody will find this useful.

**Comment by pmingram** [comment] 2017-04-27 09:30
I think I'll just stick to PHPStorm :-)

**Comment by kalieye** [comment] 2017-04-28 20:01
I think i found the problem, if uploadOnSave is set to true inside the generatedFiles configuration the file gets ignored unless you specify the extension in the "extensionsToInclude" array, i don't know if this is working as intended, copying @jsmilovic to figure this out.

For now i suggest you guys just set the uploadOnSave option to false inside the generatedFiles subsection and everything should be ok, please let me know if this helps you!

**Comment by kalieye** [comment] 2017-04-28 20:15
i just pushed a fix, please let me know if the feature is now working again

Thank you

**Comment by perfecto25** [comment] 2017-04-28 20:17
that worked. thanks for the tip!

**Closed** 2017-04-28 21:30 UTC

**Comment by AmitKKhanchandani** [comment] 2017-08-24 06:04
facing the same issue on VSCode 1.15.1 and FTP-sync 0.3.3

anyone else facing this on the latest version of VSCode, i installed this extension yesterday

**Comment by votvas** [comment] 2017-08-31 08:15
.vscode/ftp-sync.json needs the path in _generatedFiles_ :

`
...
    "generatedFiles": {
        "uploadOnSave": true,
        "extensionsToInclude": [],
        "path": "C:/Users/XXXX/Documents/VSCODE/XXXXX/"
    }
}
`

Windows 10, VSCode 1.15.1 and FTP-sync 0.3.3

**Comment by vilcuRob** [comment] 2017-09-28 10:00
@kalieye Thanks! that was it for me - maybe worth updating the description:
https://marketplace.visualstudio.com/items?itemName=lukasz-wronski.ftp-sync

**Comment by abhijeetdeb** [comment] 2018-03-04 09:30
I am unable to use the generatedFiles option to auto-upload my Sass generated CSS files. The uploadOnSave is _true_ and only the files I directly edit are getting uploaded.

```
"generatedFiles": {
        "uploadOnSave": true,
        "extensionsToInclude": [".css", ".sass"],
        "path": "C:/projects/Project Name/"
}
```

Is this feature not working anymore?

I am using VS Code 1.20.1 with ftp-sync 0.3.3 in Windows 10.

**Comment by Zamiell** [comment] 2018-07-13 05:19
I'm a first time VSCode user. After downloading and installing it, I needed an FTP extension, and this seemed to be the most popular one, so I downloaded it to give it a try.

After setting `uploadOnSave` to true in my ftp-sync.json file, it did not work, so I went online to do some searching. I stumbled upon this page, which gave me the fix: to turn the second `uploadOnSave` value inside the`generatedFiles` object to be false.

@kalieye I think that the extension could extra logic to better handle this, as the UX for new users is quite frustrating in this regard. Perhaps a helpful thing would be for the extension to automatically ignore the the second `uploadOnSave` value if the first one is set to true, or something along those lines?

**Comment by IvanMarijanovic** [comment] 2018-09-01 13:07
I had the same situation and after setting the extensionsToInclude in generatedFiles automatic upload on save is working again. 

In my case this is how I set it up:

```
"generatedFiles": {
        "uploadOnSave": true,
        "extensionsToInclude": [".php",".html"],
        "path": ""
    }
```

Ivan

**Comment by merabchik** [comment] 2019-04-11 11:05
It's not working again in VS code Version: 1.33.0 :(

**Comment by venoel** [comment] 2019-09-12 08:43
I have opposite situation. I set 
`"uploadOnSave": false,`
but files still auto uploads.
Ubuntu 18.04, VSCode v 1.38.1, ftp-sync v 0.3.9

Ftp-sync version  0.3.8 does not have this problem.

**Comment by movsar** [comment] 2019-09-22 12:11
Version 0.3.9 - automatic upload works once and then stucks when trying for the consequent times. It doesn't work until I restart the VSC. Thanks for the extension though, it's **VERY USEFUL!**

**Comment by aolamer** [comment] 2019-10-15 11:06
I had this situation and used "/" slash for the path in "generatedfiles" section and auto upload works well now
"generatedFiles": {
        "extensionsToInclude": [],
        "path": "/"
    }

**Comment by kinwebdesign** [comment] 2019-11-18 02:36
Restarting VSCode seemed to work for me 🤷

**Comment by cengizhan** [comment] 2019-12-02 10:35
> 
> 
> I have opposite situation. I set
> `"uploadOnSave": false,`
> but files still auto uploads.
> Ubuntu 18.04, VSCode v 1.38.1, ftp-sync v 0.3.9
> 
> Ftp-sync version 0.3.8 does not have this problem.

i also have this problem. i don't want my local files to be automatically uploaded. this breaks my project. i am going to disable it until it is resolved.

windows 10, vscode 1.40.2

**Comment by BidSob** [comment] 2020-04-10 09:55
> > I have opposite situation. I set
> > `"uploadOnSave": false,`
> > but files still auto uploads.
> > Ubuntu 18.04, VSCode v 1.38.1, ftp-sync v 0.3.9
> > Ftp-sync version 0.3.8 does not have this problem.
> 
> i also have this problem. i don't want my local files to be automatically uploaded. this breaks my project. i am going to disable it until it is resolved.
> 
> windows 10, vscode 1.40.2

Me too in 1.44.0

**Comment by giacomopittalis** [comment] 2020-05-19 18:22
> > > I have opposite situation. I set
> > > `"uploadOnSave": false,`
> > > but files still auto uploads.
> > > Ubuntu 18.04, VSCode v 1.38.1, ftp-sync v 0.3.9
> > > Ftp-sync version 0.3.8 does not have this problem.
> > 
> > 
> > i also have this problem. i don't want my local files to be automatically uploaded. this breaks my project. i am going to disable it until it is resolved.
> > windows 10, vscode 1.40.2
> 
> Me too in 1.44.0

Same here: win 10 vscode 1.45.1

**Comment by ProStudioMe** [comment] 2021-07-30 15:26
> I had this situation and used "/" slash for the path in "generatedfiles" section and auto upload works well now
> "generatedFiles": {
> "extensionsToInclude": [],
> "path": "/"
> }

This worked for me

**Comment by murad-faridi** [comment] 2021-10-13 06:03
### **Edit the following file to FIX:-**
For Windows: `C:\Users\(user)\.vscode\extensions\lukasz-wronski.ftp-sync-0.3.9\modules\on-generate.js`
For Linux: `home/(user)/.vscode/extensions/lukasz-wronski.ftp-sync-0.3.9/modules/on-generate.js`

### File will look like this: 

```
module.exports = function(document, getFtpSync, skipOnSaveCheck) {
if (document.uri.fsPath.indexOf(ftpconfig.rootPath().fsPath) < 0) return;
var config = ftpconfig.getConfig();
```

`if (!config.uploadOnSave) return;`                          **// <------  ADD THIS LINE TO FIX**

**Comment by szojox** [comment] 2022-08-11 08:15
> ### **Edit the following file to FIX:-**
> For Windows: `C:\Users\(user)\.vscode\extensions\lukasz-wronski.ftp-sync-0.3.9\modules\on-generate.js` For Linux: `home/(user)/.vscode/extensions/lukasz-wronski.ftp-sync-0.3.9/modules/on-generate.js`
> 
> ### File will look like this:
> ```
> module.exports = function(document, getFtpSync, skipOnSaveCheck) {
> if (document.uri.fsPath.indexOf(ftpconfig.rootPath().fsPath) < 0) return;
> var config = ftpconfig.getConfig();
> ```
> 
> `if (!config.uploadOnSave) return;` **// <------ ADD THIS LINE TO FIX**

Just use simple workaround
in settings.json - main for vscode add ->
`      "editor.codeActionsOnSave": {
            "extension.ftpsyncsingle": true
        }`

it will sync every file on save

**Comment by deltemp** [comment] 2023-09-14 16:23
"Workspace": {
    "OS": "Both Windows 11 and Pop_OS! 22.04 LTS", 
    "vscode": "1.82.1", 
    "ftp-sync": "v0.3.9"
},
"Scenario 1": {
    "uploadOnSave": false, 
    "Save the file", 
    "Right-click it", 
    "Choose 'Ftp-sync: Upload File' from the context menu", 
    "It works instantly! :-D"
},
"Scenario 2": {
    "uploadOnSave": true,    // using any of the above presented solutions
    "Save the file", 
    "Status bar freezes with: 'Ftp-sync: Uploading file.php to FTP server...'",
    "Nothing ever happens again! :_("
}
