### ISSUE TITLE
Running the contributed command:'extension.ftpsyncinit' failed.

### ISSUE THREAD

**Issue by MartinBecker** [lukasz-wronski/vscode-ftp-sync#265] opened 2018-12-05 01:17 UTC
Hi,

Similar: #108 

after some time Working with the Addon i suddenly run into an issue with the addon. I could not upload as it was asking for a config file. Then i tried to make a blank project and i received the following error.

![image](https://user-images.githubusercontent.com/6755282/49483331-0d012700-f833-11e8-8926-65ec851e4cf3.png)

## Steps to Reproduce
Not known

## Tried Solutions
- Restarting PC / VS Code 
- Disabling all Addon in Workspace
- Removing userconfig

**Comment by r3dsix** [comment] 2018-12-05 02:29
same problem for me today, how to use v0.3.5?

**Comment by ithan1985** [comment] 2018-12-05 02:32
i have the same problem i dont know why 
i have the ftp-sync.json file OK

**Comment by xueyouluo** [comment] 2018-12-05 02:41
Got the same issue.

**Comment by black-jk** [comment] 2018-12-05 02:53
Got the same issue.

**Comment by Using1174** [comment] 2018-12-05 03:41
i fix this problem by replace all  `rootPath().path` to `rootPath().fsPath` at `C:\Users\[USERNAME]\.vscode\extensions\lukasz-wronski.ftp-sync-0.3.6\modules`  directory in win10， about 8 files changed.

**Comment by black-jk** [comment] 2018-12-05 04:17
> i fix this problem by replace all `rootPath().path` to `rootPath().fsPath` at `C:\Users\[USERNAME]\.vscode\extensions\lukasz-wronski.ftp-sync-0.3.6\modules` directory in win10， about 8 files changed.

Problem solved. but  uploadOnSave function still not work  😛

**Comment by athey** [comment] 2018-12-05 05:49
I have the same problem

**Comment by mzxhtml** [comment] 2018-12-05 06:05
I have the same problem

**Comment by athey** [comment] 2018-12-05 06:21
Temporary solution:
replace all ftpconfig.rootPath().path to vscode.workspace.rootPath
replace all this.rootPath().path to vscode.workspace.rootPath

**Comment by Sibyl-lsl** [comment] 2018-12-05 08:04
我今天也遇到这个问题，怎么操作来解决这个问题？

**Comment by athey** [comment] 2018-12-05 08:16
> 我今天也遇到这个问题，怎么操作来解决这个问题？

上面的方法可以临时先解决

**Comment by athey** [comment] 2018-12-05 08:42
> 我用你的方法，把ftpconfig.rootPath（）全部换成vscode.workspace.rootPath(然后还是不行，方便加一下微信吗

rogeren

**Comment by NajSurf** [comment] 2018-12-05 10:02
Broken path is fixed now. Thanks for feedback and sorry for trouble.

@black-jk Can you tell me more about your problem with uploadOnSave? It seems to be working fine for me. The last fix was mostly for uploadOnSave not adding directories or adding them as blank files. There's a problem where uploadOnSave isn't working when size of the file wasn't changed. I'll fix this asap.

**Comment by wolfcreative** [comment] 2018-12-05 15:34
@bonovan I have a problem with "uploadOnSave". It does not work after updating to 0.3.5.

**Comment by NajSurf** [comment] 2018-12-05 15:50
Can you provide me some more information? When is it happening? How does your config look like? Are there any errors? I tried to reproduce the bug and I found out that when I run init inside a new workspace, the uploadOnSave wont work until I restart vscode, then it's working fine.

**Comment by wolfcreative** [comment] 2018-12-05 15:54
My config:
`{
    "remotePath": "project_folder",
    "host": "ip",
    "username": "project",
    "password": "project",
    "port": 22,
    "secure": false,
    "protocol": "sftp",
    "uploadOnSave": true,
    "passive": false,
    "debug": false,
    "privateKeyPath": null,
    "passphrase": null,
    "agent": null,
    "allow": [],
    "ignore": [
        "\\.vscode",
        "\\.git",
        "\\.DS_Store"
    ],
    "generatedFiles": {
        "uploadOnSave": true,
        "extensionsToInclude": [],
        "path": "project_folder"
    }
}`

The error appeared only 1 time. After the first restarting vscode. What was in it - I do not remember.

**Comment by wolfcreative** [comment] 2018-12-05 16:02
@NajSurf I tried to open an old project where everything worked before and a similar config. "uploadOnSave" does not work

**Comment by wolfcreative** [comment] 2018-12-05 18:55
Solved the problem by installing the previous version

https://github.com/lukasz-wronski/vscode-ftp-sync/issues/267#issuecomment-444599981

**Comment by NajSurf** [comment] 2018-12-06 23:49
Please check the latest version for a fix #268 It should be working fine now. Please comment if it doesn't.

**Closed** 2018-12-07 20:42 UTC

**Comment by aderchox** [comment] 2020-02-20 07:49
I've just downloaded the latest version from store but again I have this problem too.

**Comment by arkadiusz-kozub** [comment] 2020-06-10 22:51
Again same problem:
Command 'Ftp-sync: Init' resulted in an error (Running the contributed command: 'extension.ftpsyncinit' failed.)

It's after fresh extension install. VSC version is 1.46.0

**Comment by ajsixsixsix** [comment] 2021-03-04 11:32
I had the same problem on vscode 1.53 and ftp-sync 0.3.9.
downgrade ftp-sync to 0.3.5 and solved problem.

**Comment by jseguillon** [comment] 2021-03-10 14:08
had the same problem, downgrade to 0.3.5 also fixed it
