### ISSUE TITLE
automatic upload on save stopped working

### ISSUE THREAD

**Issue by felix007** [lukasz-wronski/vscode-ftp-sync#267] opened 2018-12-05 18:31 UTC
automatic upload on save stopped working after 0.3.7 update.
please check it worked great yesterday

using 
mac 10.11.6
vscode Version 1.29.1 (1.29.1)
thank you

**Comment by wolfcreative** [comment] 2018-12-05 18:54
Hey. I had such a problem. I decided to install it with the old version (https://marketplace.visualstudio.com/_apis/public/gallery/publishers/lukasz-wronski/vsextensions/ftp-sync/0.3.5/vspackage)

Do not forget to disable auto-update extensions.

**Comment by dalecosp** [comment] 2018-12-05 20:03
Looks like it's a similar issue to #154 .  A workaround there is to populate the array inside "generatedFiles" in ftp-sync.json ... the down-side, for me, being that I can't figure out what to put there for files with NO extension ...

**Comment by felix007** [comment] 2018-12-05 20:16
**Thank you wolfcreative** for the link of the old version!
now it's working again.
can you tell me how to find links to older versions of extensions? this will be a great future saver.

dalecosp, i have the right settings and it's not saving after the 0.3.7 update.
see how i"m using the details in the jason file.

`"ignore": [
        "\\.vscode",
        "\\.git",
        "\\.DS_Store"
    ],
    "generatedFiles": {
        "uploadOnSave": true,
        "extensionsToInclude": [".php", ".css", ".js", ".scss", ".css.map"],
        "path": ""
    }`

**Comment by wolfcreative** [comment] 2018-12-05 20:36
@felix007 i will explain step by step:
1. Open the extension page in the marketplace.
2. Find the right version in the "Version history".
3. Go back up and find the "Download Extension" button (the joke is that this is not a link, wtf MS).
4. In the browser downloads menu, click on the module with the right mouse button and "copy link" (I work through firefox).

What to do next makes no sense to explain.

**Comment by felix007** [comment] 2018-12-05 21:30
@wolfcreative thank you very much!

**Comment by ithan1985** [comment] 2018-12-06 00:37
the best way is reinstall vscode to fix the problem

**Comment by felix007** [comment] 2018-12-06 06:19
first thing iv"e done. doesn't work for me.

**Comment by GASOLINE** [comment] 2018-12-06 14:12
Also stopped working here. Disappointing. Hope it will be fixed because this is a really nice extension and feature. Don't know why MS does not include it as a standard feature in VSC.

**Comment by NajSurf** [comment] 2018-12-06 23:47
Please check the latest version for a fix #268. It should be working now

**Comment by felix007** [comment] 2018-12-07 07:35
@NajSurf i"m not sure what to do. updated to 0.3.7 still upload on save not working. deleted extension and installed fresh no change.
do i need to install a different version?

**Comment by NajSurf** [comment] 2018-12-07 19:04
I've just published new fixed version to the marketplace. generatedFiles was messing with uploadOnSave function. Now both functions work as planned and the problem is not occuring anymore. I'll check soon if it uploads properly when files are generated automatically by application.

**Comment by felix007** [comment] 2018-12-07 19:33
It's working again!
@NajSurf Thank you for the best vs extension!

**Comment by NajSurf** [comment] 2018-12-07 20:38
That is very good to hear :)

**Comment by felix007** [comment] 2018-12-08 23:35
Hi @NajSurf their is still a bug that is not uploading files from css folder = css/style.css  files that are generated from scss.
when i install 0.3.5 it is working great.
can you check that? 
Thank you

my json file is
{
    "remotePath": "remote path",
    "host": "host name",
    "username": "user",
    "password": "password",
    "port": 22,
    "secure": false,
    "protocol": "sftp",
    "uploadOnSave": true,
    "passive": false,
    "debug": false,
    "privateKeyPath": null,
    "passphrase": null,
    "ignore": [
        "\\.vscode",
        "\\.git",
        "\\.DS_Store"
    ],
    "generatedFiles": {
        "uploadOnSave": true,
        "extensionsToInclude": [".php", ".css", ".js", ".scss", ".css.map"],
        "path": ""
    }
}

**Comment by NajSurf** [comment] 2018-12-10 08:44
{
"remotePath": "remote path",
"host": "host name",
"username": "user",
"password": "password",
"port": 22,
"secure": false,
"protocol": "sftp",
"uploadOnSave": true,
"passive": false,
"debug": false,
"privateKeyPath": null,
"passphrase": null,
"ignore": [
"\.vscode",
"\.git",
"\.DS_Store"
],
"generatedFiles": {
"uploadOnSave": true, <---- this is no longer necessary, just delete that line.
"extensionsToInclude": [".php", ".css", ".js", ".scss", ".css.map"],
"path": "" <---- here you should provide the path to the place where generated files are, if u set this to your root folder/workspace folder then it should upload every file in it. If it's not set it wont work. I think this can be the problem.
}
}

**Comment by felix007** [comment] 2018-12-10 08:54
all the files when saved are being uploaded.. including - file.scss
only the .css files that are generated into css folder are not uploaded.
every thing worked and still working in 0.3.5.

**Comment by NajSurf** [comment] 2018-12-10 09:04
I'll try to reproduce it when I have some free time.

**Comment by felix007** [comment] 2018-12-10 09:13
Thank you

**Comment by NajSurf** [comment] 2018-12-10 19:56
Please download latest version from this github repository and check if that worked for you.

**Comment by felix007** [comment] 2018-12-10 20:18
I"ll be happy to do so but i don't know how ):
to download the zip file and change the extension to vsix?

**Comment by NajSurf** [comment] 2018-12-10 21:55
1. Download zip
2. Unpack it 
3. Go to .vscode/extensions - ".vscode" is a hidden folder
 4. Replace the ftp sync folder with the folder inside of the unpacked folder

**Comment by felix007** [comment] 2018-12-11 07:46
Great it's working again!
thank you

**Comment by NajSurf** [comment] 2018-12-11 09:11
Great :) I'll leave the issue open for couple more days if any problem occures again.

**Comment by dalecosp** [comment] 2018-12-11 16:44
Confirm, working here as well.  Thank you.

**Closed** 2018-12-26 09:36 UTC

**Comment by GASOLINE** [comment] 2019-02-10 10:03
> {
> "remotePath": "remote path",
> "host": "host name",
> "username": "user",
> "password": "password",
> "port": 22,
> "secure": false,
> "protocol": "sftp",
> "uploadOnSave": true,
> "passive": false,
> "debug": false,
> "privateKeyPath": null,
> "passphrase": null,
> "ignore": [
> ".vscode",
> ".git",
> ".DS_Store"
> ],
> "generatedFiles": {
> "uploadOnSave": true, <---- this is no longer necessary, just delete that line.
> "extensionsToInclude": [".php", ".css", ".js", ".scss", ".css.map"],
> "path": "" <---- here you should provide the path to the place where generated files are, if u set this to your root folder/workspace folder then it should upload every file in it. If it's not set it wont work. I think this can be the problem.
> }
> }

If i set path like /build it works, but only for that folder. Than my other files in / are ignored. Confusing.
