### ISSUE TITLE
Cant download

### ISSUE THREAD

**Issue by kasik96** [lukasz-wronski/vscode-ftp-sync#14] opened 2015-12-11 07:23 UTC
When i set to Force or Full download from FTP, it downloads like half, and do this error:
![screen shot 2015-12-11 at 08 21 36](https://cloud.githubusercontent.com/assets/7235992/11738150/578e0cba-9fe0-11e5-9165-7f3bab5e3455.png)

**Comment by lukasz-wronski** [comment] 2016-01-10 13:12
Can I see the files list that are being downloaded? Can you determine which file from the list is causing the problem? Does it have unusual name or chmod or large size etc?

**Comment by kasik96** [comment] 2016-01-10 13:14
I have here only basic things. I try it on two my FTP servers and dont work on any of it. 
![screen shot 2016-01-10 at 14 13 37](https://cloud.githubusercontent.com/assets/7235992/12221656/668149cc-b7a4-11e5-971c-f31ef4a4cae1.png)
![screen shot 2016-01-10 at 14 13 42](https://cloud.githubusercontent.com/assets/7235992/12221657/66a77e44-b7a4-11e5-804d-badfaa79afeb.png)

**Comment by lukasz-wronski** [comment] 2016-01-10 13:38
Can you do following steps: 

1) Attach ftp settings to your ftp server on remote and to new empty directory on local side
2) Run "Ftp sync remote to local" with option "Force"
3) Choose to "Review" the list of files to be downloaded 
4) Store the list of files somewhere
5) Run "Ftp-sync: Commit" command to start downloading files
6) Check which is the first file on the list that was not downloaded?

This way we can determine which of the files is causing the problem.

Alternatively can you mail me access to FTP server that the problem is present on so I can try to download it and debug the extension?

**Comment by kasik96** [comment] 2016-01-10 14:11
Ok, here it is:
[data.zip](https://github.com/lukasz-wronski/vscode-ftp-sync/files/84121/data.zip)
And this is error:
![screen shot 2016-01-10 at 15 09 35](https://cloud.githubusercontent.com/assets/7235992/12221903/5efafa42-b7ac-11e5-8b09-3c7b46910e20.png)
And the result (it downloads only empty folders):
![screen shot 2016-01-10 at 15 09 43](https://cloud.githubusercontent.com/assets/7235992/12221907/694c919a-b7ac-11e5-89ce-a37b3e3918f7.png)

**Comment by lukasz-wronski** [comment] 2016-01-10 14:14
Were all directories from `dirsToAdd` list created or some are missing?

**Comment by lukasz-wronski** [comment] 2016-01-10 14:39
Just published `0.2.3` with the fix. Thanks for help on resolving it.

**Closed** 2016-01-10 14:38 UTC
Labels: bug
